AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  GrafanaInstance:
    AllowedValues:
      - t3.nano
      - t3.micro
      - t2.nano
      - t2.micro
    ConstraintDescription: It must be a valid EC2 Type
    Default: t2.micro
    Description: Instance Type for Grafana
    Type: String
#   BucketNameParameter:
#     Type: String
#     Description: eb-test

Resources:


  # S3Bucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     AccessControl: Private
  #     # BucketName: !Ref BucketNameParameter
  #     BucketName: eb-test-jsanchez
  #     VersioningConfiguration:
  #       Status: Enabled
  #     # Tags: eb-test

# To add the initial bucket with the zip file
  # S3CustomResource:
  #   Type: Custom::S3CustomResource
  #   Properties:
  #     ServiceToken: !GetAtt AWSLambdaFunction.Arn
  #     the_bucket: !Ref SampleS3Bucket
  #     dirs_to_create: !Ref DirsToCreate

  ebApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Application

  ebApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: ebApplication
      Description: AWS ElasticBeanstalk Grafana Application Version
      SourceBundle:
        # S3Bucket: !Sub "eb-jsanchez"
        S3Bucket: !Sub "teravision-eb-test4-jsanchez"
        S3Key: deploy.zip

  ebConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: ebApplication
      Description: AWS ElasticBeanstalk Configuration
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '2'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: !Ref GrafanaInstance
      # - Namespace: aws:ec2:instances
      #   OptioName: InstanceType
      #   Value: 't3.nano,t3.micro'      
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref MyInstanceProfile        
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.16.6 running Docker 19.03.13-ce

  ebEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: ebApplication
      Description: AWS ElasticBeanstalk Environment
      TemplateName:
        Ref: ebConfigurationTemplate
      VersionLabel:
        Ref: ebApplicationVersion

  MyInstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Beanstalk EC2 role
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
        
  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref MyInstanceRole

