# FROM grafana/grafana:${TAG_GRAFANA}
ARG VERSION=7.5.2
# FROM grafana/grafana:7.5.2
FROM grafana/grafana:${VERSION}
MAINTAINER Johannes Sanchez <johallengineer@gmail.com>

EXPOSE 3000
# Puedo incluir un CICD en AWS para ? o para el ejercicio no es necesario.
# Y si puedo incluir el CICD, hay restricciones para hacerlo outside AWS, por ejemplo con Github Actions? pensando en reducir el costo del pipeline en AWS.
